import Link from "next/link"; import type{ButtonHTMLAttributes,InputHTMLAttributes,ReactNode,SelectHTMLAttributes}from"react";
export function Button({children,variant="primary",className="",...p}:ButtonHTMLAttributes<HTMLButtonElement>&{variant?:"primary"|"secondary"|"danger"}){const c={primary:"bg-blue-600 text-white hover:bg-blue-700",secondary:"bg-white text-slate-700 border border-slate-200 hover:bg-slate-50",danger:"bg-rose-50 text-rose-700"};return <button className={`inline-flex min-h-11 items-center justify-center rounded-xl px-5 font-bold transition ${c[variant]} ${className}`} {...p}>{children}</button>}
export const Card=({children,className=""}:{children:ReactNode;className?:string})=><section className={`card ${className}`}>{children}</section>;
export function Badge({children,tone="blue"}:{children:ReactNode;tone?:"blue"|"mint"|"gray"|"red"}){const c={blue:"bg-blue-50 text-blue-700",mint:"bg-teal-50 text-teal-700",gray:"bg-slate-100 text-slate-600",red:"bg-rose-50 text-rose-700"};return <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-bold ${c[tone]}`}>{children}</span>}
export function Input({label,...p}:InputHTMLAttributes<HTMLInputElement>&{label:string}){return <label><span className="mb-2 block text-sm font-bold text-slate-700">{label}</span><input className="h-12 w-full rounded-xl border border-slate-200 px-4 outline-none focus:border-blue-500 focus:ring-4 focus:ring-blue-100" {...p}/></label>}
export function Select({label,children,...p}:SelectHTMLAttributes<HTMLSelectElement>&{label:string;children:ReactNode}){return <label><span className="mb-2 block text-sm font-bold text-slate-700">{label}</span><select className="h-12 w-full rounded-xl border border-slate-200 bg-white px-4 outline-none focus:border-blue-500 focus:ring-4 focus:ring-blue-100" {...p}>{children}</select></label>}
export const Table=({headers,children}:{headers:string[];children:ReactNode})=><div className="table-wrap"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div>;
export function Modal({open,title,children}:{open?:boolean;title:string;children:ReactNode}){if(!open)return null;return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4"><div className="card w-full max-w-lg p-6" role="dialog" aria-modal="true"><h2 className="text-xl font-extrabold">{title}</h2><div className="mt-4">{children}</div></div></div>}
export function PageHeader({eyebrow,title,description,action}:{eyebrow?:string;title:string;description:string;action?:ReactNode}){return <div className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div>{eyebrow&&<p className="mb-2 text-sm font-extrabold text-blue-600">{eyebrow}</p>}<h1 className="text-2xl font-black tracking-tight sm:text-3xl">{title}</h1><p className="mt-2 text-sm text-slate-500">{description}</p></div>{action}</div>}
export function Header({role="student"}:{role?:"student"|"admin"|"teacher"}){const links=role==="admin"?[["/admin","대시보드"],["/admin/courses","강좌 관리"],["/admin/applications","신청 현황"],["/admin/students","학생 관리"],["/admin/teachers","교사 관리"],["/admin/settings","신청 설정"]]:role==="teacher"?[["/teacher","교사 홈"],["/teacher/applications","신청자 명단"]]:[["/","본인 확인"],["/courses","수강신청"]];return <header className="bg-[#102a43] text-white"><div className="container flex min-h-16 flex-wrap items-center justify-between gap-3 py-3"><Link href="/" className="flex items-center gap-3 font-black"><span className="grid h-9 w-9 place-items-center rounded-xl bg-teal-400 text-[#102a43]">방</span>방과후 신청</Link><nav className="flex items-center gap-1 overflow-x-auto">{links.map(([h,l])=><Link className="rounded-lg px-3 py-2 text-sm font-bold text-slate-200 hover:bg-white/10" href={h} key={h}>{l}</Link>)}{role!=="student"&&<form action="/auth/logout" method="post"><button className="rounded-lg px-3 py-2 text-sm font-bold text-slate-200 hover:bg-white/10">로그아웃</button></form>}</nav></div></header>}
export const AppShell=({children,role}:{children:ReactNode;role:"student"|"admin"|"teacher"})=><div className="shell"><Header role={role}/><main className="main container">{children}</main><footer className="border-t border-slate-200 py-6 text-center text-xs text-slate-400">© 2026 방과후 신청 · 학교 방과후학교 운영 시스템</footer></div>;
